version: '3'
services:
  resources-api:
    build: ./resource-api/src
    volumes:
      - ./:/usr/src/application:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"  